server:
  port: 8080
spring:
  application:
    name: product
  
  profiles:
    active: "prod"

  datasource:
    driverClassName: org.postgresql.Driver
    username: admin
    password: password
    url: jdbc:postgresql://localhost:5432/fashion-shop
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # hibernate:
    #   ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"