server:
  port: 8071
spring: 
  application: 
    name: configserver

  profiles:
      # active: native
      active: git
  cloud:
    config:
      server:
        # native:
        #   search-locations: "classpath:/config"
          # search-locations: "file:///Users/quandoan/Documents/m2_java_projects/Fashion-Shop-Spring/configserver/src/main/resources/config/"
        git:
          uri: "https://github.com/minhquandoan/Fashion-Shop-Config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSW:guest}

management:
  enpoint:
    monitor: 
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
          enabled: true
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    