server:
  port: 8071
spring: 
  application: 
    name: configserver

  profiles:
      # active: native
      active: git
  cloud:
    config:
      server:
        # native:
        #   search-locations: "classpath:/config"
          # search-locations: "file:///Users/quandoan/Documents/m2_java_projects/Fashion-Shop-Spring/configserver/src/main/resources/config/"
        git:
          uri: "git@github.com:minhquandoan/Fashion-Shop-Config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true